
// NCNR INC > ontario
// {
//     "businessName": "NCNR INC",
//     "addressLine2": "SEBASTOPOL, CA"
// }
res=[
    {
      "poseidonId": -7155346944817784000,
      "uccFilings": [],
      "newBusinessFilings": [],
      "usCorpFilings": [
        {
          "poseidonId": -7155346944817784000,
          "ein": "00-0000000",
          "name": "NCNR UNITED INC",
          "rawName": "NCNR UNITED, INC",
          "corpFileKey": "FLP11000017651",
          "corpStatus": "ACTIVE",
          "corpStatusDate": "03/09/2023",
          "corpType": "DOMESTIC FOR PROFIT",
          "registryNumber": "P11000017651",
          "stateCode": "FL",
          "statute": "",
          "stateTaxId": "",
          "term": "",
          "fileData": null,
          "fileDataDate": "4/21/2023",
          "filingDate": "2/18/2011",
          "incorporationState": "FL",
          "filingType": "2023 ANNUAL REPORT",
          "jurisdiction": "",
          "lastReportedDate": "03/09/2023",
          "expireDate": "",
          "contacts": [],
          "officers": [
            {
              "fileDate": null,
              "name": {
                "nameSuffix": "",
                "nameHashReq1": "-3454389433692158413",
                "nameFirst": "Patel",
                "nameGender": "N",
                "nameLast": "Chetan",
                "nameMiddle": "",
                "nameRaw": "PATEL CHETAN",
                "nameProblemCodes": "NS01,NS05,NS06",
                "nameHashOpt5": -2610493489762756000,
                "namePrefix": "",
                "nameHashOpt4": 4199624103711681000,
                "nameSuffixNorm": "",
                "tahoeId": null
              },
              "title": "REGISTERED AGENT,PRESIDENT",
              "startDate": "20230501",
              "status": null,
              "address": {
                "city": "West Melbourne",
                "state": "FL",
                "zip": "32904",
                "county": "Brevard",
                "country": "",
                "addressHash": "5252806473007113564",
                "houseNumber": "1431",
                "streetName": "Tamango",
                "streetPostDirection": "",
                "streetPreDirection": "",
                "unit": "",
                "unitType": "",
                "addressLine1": "1431 Tamango",
                "addressLine2": "West Melbourne, FL 32904",
                "fullAddress": "1431 Tamango; West Melbourne, FL 32904"
              },
              "mailingAddress": null,
              "fax": null,
              "email": null
            },
            {
              "fileDate": null,
              "name": {
                "nameSuffix": "",
                "nameHashReq1": "-1025867443389308483",
                "nameFirst": "Chetan",
                "nameGender": "M",
                "nameLast": "Patel",
                "nameMiddle": "",
                "nameRaw": "CHETAN PATEL",
                "nameProblemCodes": "NS01,NS05,NS06",
                "nameHashOpt5": -7715521356523862000,
                "namePrefix": "",
                "nameHashOpt4": 2248495178232553700,
                "nameSuffixNorm": "",
                "tahoeId": null
              },
              "title": "REGISTERED AGENT,PRESIDENT",
              "startDate": "20201107",
              "status": null,
              "address": {
                "city": "West Melbourne",
                "state": "FL",
                "zip": "32904",
                "county": "Brevard",
                "country": "",
                "addressHash": "5252806473007113564",
                "houseNumber": "1431",
                "streetName": "Tamango",
                "streetPostDirection": "",
                "streetPreDirection": "",
                "unit": "",
                "unitType": "",
                "addressLine1": "1431 Tamango",
                "addressLine2": "West Melbourne, FL 32904",
                "fullAddress": "1431 Tamango; West Melbourne, FL 32904"
              },
              "mailingAddress": null,
              "fax": null,
              "email": null
            },
            {
              "fileDate": null,
              "name": {
                "nameSuffix": "",
                "nameHashReq1": "-1025867443389308483",
                "nameFirst": "Nila",
                "nameGender": "F",
                "nameLast": "Patel",
                "nameMiddle": "C",
                "nameRaw": "PATEL NILA C",
                "nameProblemCodes": "NS01,NS05,NS06",
                "nameHashOpt5": 6266248197523145000,
                "namePrefix": "",
                "nameHashOpt4": 1077980525668992800,
                "nameSuffixNorm": "",
                "tahoeId": "G5417712922840442434"
              },
              "title": "DIRECTOR",
              "startDate": "20230501",
              "status": null,
              "address": {
                "city": "Melbourne",
                "state": "FL",
                "zip": "32904",
                "county": "Brevard",
                "country": "",
                "addressHash": "-2390995247195940355",
                "houseNumber": "1431",
                "streetName": "Tamango",
                "streetPostDirection": "",
                "streetPreDirection": "",
                "unit": "",
                "unitType": "",
                "addressLine1": "1431 Tamango",
                "addressLine2": "Melbourne, FL 32904",
                "fullAddress": "1431 Tamango; Melbourne, FL 32904"
              },
              "mailingAddress": null,
              "fax": null,
              "email": null
            }
          ],
          "phones": null,
          "emails": [],
          "stock": {
            "stateCode": "",
            "stockClass": "",
            "stockDate": "",
            "stockParValue": "",
            "stockRestrictInd": "",
            "stockSharesAuth": ""
          },
          "merger": {
            "eventDescription": "",
            "mergeDate": "",
            "mergedCorpId": "",
            "mergedCorpName": "",
            "stateCode": "",
            "survivingCorpId": ""
          },
          "history": {
            "amendmentDate": "20230309",
            "amendmentType": "ANNUAL REPORT",
            "corpFileKey": "FLP11000017651",
            "historyEvent": null,
            "stateCode": "FL"
          },
          "alternateName": {
            "name": "",
            "amendmentDate": "",
            "certificationDate": "",
            "consentName": "",
            "corpFileKey": "",
            "expireDate": "",
            "filingDate": "",
            "nameType": "",
            "purpose": "",
            "registryNumber": "",
            "renewalDate": "",
            "similarAltName": "",
            "stateCode": "",
            "stateOfOrigin": "",
            "status": "",
            "statusDate": "",
            "xRef1Name": "",
            "xRef2Name": ""
          },
          "corpMainAddresses": [
            {
              "city": "Fl 32177 Null",
              "state": "",
              "zip": "",
              "county": "",
              "country": "",
              "addressHash": "4523321872779958702",
              "houseNumber": "",
              "streetName": "NULL US HIGHWAY 17",
              "streetPostDirection": "S",
              "streetPreDirection": "",
              "unit": "",
              "unitType": "",
              "addressLine1": "NULL US HIGHWAY 17 S",
              "addressLine2": "Fl 32177 Null",
              "fullAddress": "NULL US HIGHWAY 17 S; Fl 32177 Null"
            },
            {
              "city": "Fl 32177 Null",
              "state": "",
              "zip": "",
              "county": "",
              "country": "",
              "addressHash": "7427778618647157846",
              "houseNumber": "S",
              "streetName": "18TH NULL",
              "streetPostDirection": "",
              "streetPreDirection": "",
              "unit": "",
              "unitType": "",
              "addressLine1": "S 18TH NULL",
              "addressLine2": "Fl 32177 Null",
              "fullAddress": "S 18TH NULL; Fl 32177 Null"
            },
            {
              "city": "Fl 33810 Null",
              "state": "",
              "zip": "",
              "county": "",
              "country": "",
              "addressHash": "3515350846750043756",
              "houseNumber": "",
              "streetName": "",
              "streetPostDirection": "",
              "streetPreDirection": "",
              "unit": "",
              "unitType": "",
              "addressLine1": "",
              "addressLine2": "Fl 33810 Null",
              "fullAddress": "Fl 33810 Null"
            }
          ]
        }
      ]
    },
    {
      "poseidonId": -5629186126571251000,
      "uccFilings": [],
      "newBusinessFilings": [],
      "usCorpFilings": [
        {
          "poseidonId": -5629186126571251000,
          "ein": "",
          "name": "NCNR CORPORATION",
          "rawName": "NCNR CORPORATION",
          "corpFileKey": "NY4864119",
          "corpStatus": "ACTIVE",
          "corpStatusDate": "12/15/2015",
          "corpType": "DOMESTIC BUSINESS CORPORATION",
          "registryNumber": "4864119",
          "stateCode": "NY",
          "statute": "",
          "stateTaxId": "",
          "term": "PERPETUAL",
          "fileData": null,
          "fileDataDate": "5/19/2023",
          "filingDate": "12/15/2015",
          "incorporationState": "",
          "filingType": "CERTIFICATE OF INCORPORATION",
          "jurisdiction": "NY",
          "lastReportedDate": "",
          "expireDate": "",
          "contacts": [],
          "officers": [
            {
              "fileDate": null,
              "name": {
                "nameSuffix": "",
                "nameHashReq1": "8730378433752772970",
                "nameFirst": "",
                "nameGender": "U",
                "nameLast": "Corporation",
                "nameMiddle": "",
                "nameRaw": "THE CORPORATION",
                "nameProblemCodes": "NS02,NE05",
                "nameHashOpt5": -2438413920367679500,
                "namePrefix": "The",
                "nameHashOpt4": -5982587913205703000,
                "nameSuffixNorm": "",
                "tahoeId": null
              },
              "title": "PROCESSOR",
              "startDate": "20201107",
              "status": null,
              "address": {
                "city": "Minoa",
                "state": "NY",
                "zip": "13116",
                "county": "Onondaga",
                "country": "",
                "addressHash": "-6344364466274260893",
                "houseNumber": "103",
                "streetName": "Kensington High",
                "streetPostDirection": "",
                "streetPreDirection": "",
                "unit": "",
                "unitType": "",
                "addressLine1": "103 Kensington High",
                "addressLine2": "Minoa, NY 13116",
                "fullAddress": "103 Kensington High; Minoa, NY 13116"
              },
              "mailingAddress": null,
              "fax": null,
              "email": null
            }
          ],
          "phones": null,
          "emails": [],
          "stock": {
            "stateCode": "",
            "stockClass": "",
            "stockDate": "",
            "stockParValue": "",
            "stockRestrictInd": "",
            "stockSharesAuth": ""
          },
          "merger": {
            "eventDescription": "",
            "mergeDate": "",
            "mergedCorpId": "",
            "mergedCorpName": "",
            "stateCode": "",
            "survivingCorpId": ""
          },
          "history": {
            "amendmentDate": "20151215",
            "amendmentType": "MICROFILM NUMBER: 151215010027",
            "corpFileKey": "NY4864119",
            "historyEvent": "CERTIFICATE OF INCORPORATION",
            "stateCode": "NY"
          },
          "alternateName": {
            "name": "",
            "amendmentDate": "",
            "certificationDate": "",
            "consentName": "",
            "corpFileKey": "",
            "expireDate": "",
            "filingDate": "",
            "nameType": "",
            "purpose": "",
            "registryNumber": "",
            "renewalDate": "",
            "similarAltName": "",
            "stateCode": "",
            "stateOfOrigin": "",
            "status": "",
            "statusDate": "",
            "xRef1Name": "",
            "xRef2Name": ""
          },
          "corpMainAddresses": [
            {
              "city": "Fl 32177 Null",
              "state": "",
              "zip": "",
              "county": "",
              "country": "",
              "addressHash": "4523321872779958702",
              "houseNumber": "",
              "streetName": "NULL US HIGHWAY 17",
              "streetPostDirection": "S",
              "streetPreDirection": "",
              "unit": "",
              "unitType": "",
              "addressLine1": "NULL US HIGHWAY 17 S",
              "addressLine2": "Fl 32177 Null",
              "fullAddress": "NULL US HIGHWAY 17 S; Fl 32177 Null"
            },
            {
              "city": "Fl 32177 Null",
              "state": "",
              "zip": "",
              "county": "",
              "country": "",
              "addressHash": "7427778618647157846",
              "houseNumber": "S",
              "streetName": "18TH NULL",
              "streetPostDirection": "",
              "streetPreDirection": "",
              "unit": "",
              "unitType": "",
              "addressLine1": "S 18TH NULL",
              "addressLine2": "Fl 32177 Null",
              "fullAddress": "S 18TH NULL; Fl 32177 Null"
            },
            {
              "city": "Fl 33810 Null",
              "state": "",
              "zip": "",
              "county": "",
              "country": "",
              "addressHash": "3515350846750043756",
              "houseNumber": "",
              "streetName": "",
              "streetPostDirection": "",
              "streetPreDirection": "",
              "unit": "",
              "unitType": "",
              "addressLine1": "",
              "addressLine2": "Fl 33810 Null",
              "fullAddress": "Fl 33810 Null"
            }
          ]
        }
      ]
    },
    {
      "poseidonId": 3592921567383634000,
      "uccFilings": [],
      "newBusinessFilings": [],
      "usCorpFilings": [
        {
          "poseidonId": 3592921567383634000,
          "ein": "00-0000000",
          "name": "NCNR ENTERPRISES LLC",
          "rawName": "NCNR ENTERPRISES, LLC",
          "corpFileKey": "FLL08000014996",
          "corpStatus": "INACTIVE",
          "corpStatusDate": "09/25/2009",
          "corpType": "FLORIDA LIMITED LIABILITY",
          "registryNumber": "L08000014996",
          "stateCode": "FL",
          "statute": "",
          "stateTaxId": "",
          "term": "",
          "fileData": null,
          "fileDataDate": "7/14/2015",
          "filingDate": "2/11/2008",
          "incorporationState": "FL",
          "filingType": "ADMIN DISSOLUTION FOR ANNUAL REPORT",
          "jurisdiction": "",
          "lastReportedDate": "09/25/2009",
          "expireDate": "",
          "contacts": [],
          "officers": [
            {
              "fileDate": null,
              "name": {
                "nameSuffix": "",
                "nameHashReq1": "-1670511555931685164",
                "nameFirst": "Josh",
                "nameGender": "M",
                "nameLast": "Lemaster",
                "nameMiddle": "P",
                "nameRaw": "LEMASTER JOSH P",
                "nameProblemCodes": "NS01,NS05,NS06",
                "nameHashOpt5": -1353086055670685400,
                "namePrefix": "",
                "nameHashOpt4": 745645431820701300,
                "nameSuffixNorm": "",
                "tahoeId": "G6652657047933417441"
              },
              "title": "REGISTERED AGENT",
              "startDate": "20230403",
              "status": null,
              "address": {
                "city": "Jacksonville",
                "state": "FL",
                "zip": "32257",
                "county": "Duval",
                "country": "",
                "addressHash": "-2661926410004144404",
                "houseNumber": "3430",
                "streetName": "Kori",
                "streetPostDirection": "",
                "streetPreDirection": "",
                "unit": "1",
                "unitType": "Ste",
                "addressLine1": "3430 Kori, Ste 1",
                "addressLine2": "Jacksonville, FL 32257",
                "fullAddress": "3430 Kori, Ste 1; Jacksonville, FL 32257"
              },
              "mailingAddress": null,
              "fax": null,
              "email": null
            },
            {
              "fileDate": "",
              "name": {
                "nameSuffix": "",
                "nameHashReq1": "-6352774355461976988",
                "nameFirst": "",
                "nameGender": "U",
                "nameLast": "Nettles",
                "nameMiddle": "",
                "nameRaw": "NETTLES",
                "nameProblemCodes": "NS01,NS06",
                "nameHashOpt5": -3152381213224462000,
                "namePrefix": "",
                "nameHashOpt4": -8106659747014972000,
                "nameSuffixNorm": "",
                "tahoeId": null
              },
              "title": "",
              "startDate": "20160901",
              "status": "",
              "address": null,
              "mailingAddress": null,
              "fax": "21462151",
              "email": null
            },
            {
              "fileDate": null,
              "name": {
                "nameSuffix": "",
                "nameHashReq1": "8975237645844108127",
                "nameFirst": "Eric",
                "nameGender": "M",
                "nameLast": "Caballero",
                "nameMiddle": "",
                "nameRaw": "ERIC CABALLERO",
                "nameProblemCodes": "NS01,NS05,NS06",
                "nameHashOpt5": -7173473298736318000,
                "namePrefix": "",
                "nameHashOpt4": 6324317890994082000,
                "nameSuffixNorm": "",
                "tahoeId": null
              },
              "title": "MGRM",
              "startDate": "20201107",
              "status": null,
              "address": {
                "city": "Lakeland",
                "state": "FL",
                "zip": "33810",
                "county": "Polk",
                "country": "",
                "addressHash": "-6114865870890429116",
                "houseNumber": "1830",
                "streetName": "Prairie Dunes",
                "streetPostDirection": "N",
                "streetPreDirection": "",
                "unit": "",
                "unitType": "",
                "addressLine1": "1830 Prairie Dunes N",
                "addressLine2": "Lakeland, FL 33810",
                "fullAddress": "1830 Prairie Dunes N; Lakeland, FL 33810"
              },
              "mailingAddress": null,
              "fax": null,
              "email": null
            },
            {
              "fileDate": null,
              "name": {
                "nameSuffix": "",
                "nameHashReq1": "-6352774355461976988",
                "nameFirst": "Troy",
                "nameGender": "M",
                "nameLast": "Nettles",
                "nameMiddle": "",
                "nameRaw": "TROY NETTLES",
                "nameProblemCodes": "NS01,NS05,NS06",
                "nameHashOpt5": -5695092284277023000,
                "namePrefix": "",
                "nameHashOpt4": -6317109988529207000,
                "nameSuffixNorm": "",
                "tahoeId": null
              },
              "title": "MGRM",
              "startDate": "20201107",
              "status": null,
              "address": {
                "city": "Palatka",
                "state": "FL",
                "zip": "32177",
                "county": "Putnam",
                "country": "",
                "addressHash": "3459932959267028420",
                "houseNumber": "400",
                "streetName": "18th",
                "streetPostDirection": "",
                "streetPreDirection": "S",
                "unit": "",
                "unitType": "",
                "addressLine1": "400 S 18th",
                "addressLine2": "Palatka, FL 32177",
                "fullAddress": "400 S 18th; Palatka, FL 32177"
              },
              "mailingAddress": null,
              "fax": null,
              "email": null
            },
            {
              "fileDate": "",
              "name": {
                "nameSuffix": "",
                "nameHashReq1": "8975237645844108127",
                "nameFirst": "",
                "nameGender": "U",
                "nameLast": "Caballero",
                "nameMiddle": "",
                "nameRaw": "CABALLERO",
                "nameProblemCodes": "NS01,NS06",
                "nameHashOpt5": -4152237653087394300,
                "namePrefix": "",
                "nameHashOpt4": 5595766351255666000,
                "nameSuffixNorm": "",
                "tahoeId": null
              },
              "title": "",
              "startDate": "20160901",
              "status": "",
              "address": null,
              "mailingAddress": null,
              "fax": "21462151",
              "email": null
            },
            {
              "fileDate": null,
              "name": {
                "nameSuffix": "",
                "nameHashReq1": "7315409445237914095",
                "nameFirst": "Caballero",
                "nameGender": "U",
                "nameLast": "Eric",
                "nameMiddle": "",
                "nameRaw": "CABALLERO ERIC",
                "nameProblemCodes": "NS01,NS06",
                "nameHashOpt5": -1835387092993164800,
                "namePrefix": "",
                "nameHashOpt4": -8521738768351222000,
                "nameSuffixNorm": "",
                "tahoeId": null
              },
              "title": "MGRM",
              "startDate": "20230403",
              "status": null,
              "address": {
                "city": "Lakeland",
                "state": "FL",
                "zip": "33810",
                "county": "Polk",
                "country": "",
                "addressHash": "-6114865870890429116",
                "houseNumber": "1830",
                "streetName": "Prairie Dunes",
                "streetPostDirection": "N",
                "streetPreDirection": "",
                "unit": "",
                "unitType": "",
                "addressLine1": "1830 Prairie Dunes N",
                "addressLine2": "Lakeland, FL 33810",
                "fullAddress": "1830 Prairie Dunes N; Lakeland, FL 33810"
              },
              "mailingAddress": null,
              "fax": null,
              "email": null
            },
            {
              "fileDate": null,
              "name": {
                "nameSuffix": "",
                "nameHashReq1": "3978216955681435352",
                "nameFirst": "Nettles",
                "nameGender": "U",
                "nameLast": "Troy",
                "nameMiddle": "",
                "nameRaw": "NETTLES TROY",
                "nameProblemCodes": "NS01,NS06",
                "nameHashOpt5": 8617357505925726000,
                "namePrefix": "",
                "nameHashOpt4": -3700127447887958000,
                "nameSuffixNorm": "",
                "tahoeId": null
              },
              "title": "MGRM",
              "startDate": "20230403",
              "status": null,
              "address": {
                "city": "Palatka",
                "state": "FL",
                "zip": "32177",
                "county": "Putnam",
                "country": "",
                "addressHash": "3459932959267028420",
                "houseNumber": "400",
                "streetName": "18th",
                "streetPostDirection": "",
                "streetPreDirection": "S",
                "unit": "",
                "unitType": "",
                "addressLine1": "400 S 18th",
                "addressLine2": "Palatka, FL 32177",
                "fullAddress": "400 S 18th; Palatka, FL 32177"
              },
              "mailingAddress": null,
              "fax": null,
              "email": null
            }
          ],
          "phones": null,
          "emails": [],
          "stock": {
            "stateCode": "",
            "stockClass": "",
            "stockDate": "",
            "stockParValue": "",
            "stockRestrictInd": "",
            "stockSharesAuth": ""
          },
          "merger": {
            "eventDescription": "",
            "mergeDate": "",
            "mergedCorpId": "",
            "mergedCorpName": "",
            "stateCode": "",
            "survivingCorpId": ""
          },
          "history": {
            "amendmentDate": "20090925",
            "amendmentType": "ADMIN DISSOLUTION FOR ANNUAL REPORT",
            "corpFileKey": "FLL08000014996",
            "historyEvent": null,
            "stateCode": "FL"
          },
          "alternateName": {
            "name": "GREATMATTRESSBUYS.COM",
            "amendmentDate": null,
            "certificationDate": null,
            "consentName": null,
            "corpFileKey": "FLL08000014996",
            "expireDate": "12/31/2013",
            "filingDate": "02/12/2008",
            "nameType": "FICTITIOUS NAME",
            "purpose": null,
            "registryNumber": "G08043900591",
            "renewalDate": null,
            "similarAltName": null,
            "stateCode": "FL",
            "stateOfOrigin": null,
            "status": "ACTIVE",
            "statusDate": null,
            "xRef1Name": null,
            "xRef2Name": null
          },
          "corpMainAddresses": [
            {
              "city": "Fl 32177 Null",
              "state": "",
              "zip": "",
              "county": "",
              "country": "",
              "addressHash": "4523321872779958702",
              "houseNumber": "",
              "streetName": "NULL US HIGHWAY 17",
              "streetPostDirection": "S",
              "streetPreDirection": "",
              "unit": "",
              "unitType": "",
              "addressLine1": "NULL US HIGHWAY 17 S",
              "addressLine2": "Fl 32177 Null",
              "fullAddress": "NULL US HIGHWAY 17 S; Fl 32177 Null"
            },
            {
              "city": "Fl 32177 Null",
              "state": "",
              "zip": "",
              "county": "",
              "country": "",
              "addressHash": "7427778618647157846",
              "houseNumber": "S",
              "streetName": "18TH NULL",
              "streetPostDirection": "",
              "streetPreDirection": "",
              "unit": "",
              "unitType": "",
              "addressLine1": "S 18TH NULL",
              "addressLine2": "Fl 32177 Null",
              "fullAddress": "S 18TH NULL; Fl 32177 Null"
            },
            {
              "city": "Fl 33810 Null",
              "state": "",
              "zip": "",
              "county": "",
              "country": "",
              "addressHash": "3515350846750043756",
              "houseNumber": "",
              "streetName": "",
              "streetPostDirection": "",
              "streetPreDirection": "",
              "unit": "",
              "unitType": "",
              "addressLine1": "",
              "addressLine2": "Fl 33810 Null",
              "fullAddress": "Fl 33810 Null"
            }
          ]
        }
      ]
    }
  ]




  x={
    "workplaceRecords": [
      {
        "requestId": 1939394947293749200,
        "tahoeIdMatches": [],
        "tahoeAppend": null,
        "ssn": "",
        "fullName": "JOHN DOE",
        "salutation": "",
        "firstName": "JOHN",
        "middleName": "",
        "lastName": "DOE",
        "suffix": "",
        "professionalTitles": "CLIENT PARTNER,DIRECTOR OF STRATEGY,PRODUCT MANAGER - ECOSYSTEM,FOUNDER,ADJUNCT PROFESSOR OF BUSINESS,STRATEGIST AND PRESIDENT,CONSULTING MANAGER (STRATEGY CONSULTANT),PROJECT MANAGEMENT CONSULTANT,TELECOMMUNICATIONS ANALYST,NEW ASSOCIATE TECHNOLOGY ANALYST",
        "names": [
          {
            "prefix": "",
            "firstName": "JOHN",
            "middleName": "",
            "lastName": "DOE",
            "suffix": "",
            "ssn": "",
            "fullName": "JOHN DOE"
          }
        ],
        "addresses": [],
        "phoneNumbers": [],
        "phoneTypes": {
          "desk": "",
          "corporate": "",
          "cell": ""
        },
        "emailAddresses": [],
        "companies": [],
        "education": [
          {
            "school": "Springfield University",
            "schoolMatch": "",
            "degree": "BS",
            "degreeMatch": "",
            "major": "",
            "startDate": "1988",
            "schoolStartDate": "0001-01-01T00:00:00",
            "endDate": "1992",
            "schoolEndDate": "0001-01-01T00:00:00"
          },
          {
            "school": "Serious School of Business",
            "schoolMatch": "",
            "degree": "MBA",
            "degreeMatch": "",
            "major": "",
            "startDate": "1992",
            "schoolStartDate": "0001-01-01T00:00:00",
            "endDate": "1995",
            "schoolEndDate": "0001-01-01T00:00:00"
          }
        ],
        "currentEmployment": [
          {
            "employer": "HOT DOG, LLC",
            "jobTitle": "DIRECTOR",
            "level": "DIRECTOR-LEVEL",
            "department": "Marketing and Product",
            "houseNumber": "",
            "streetDirection": "",
            "streetName": "",
            "streetType": "",
            "streetPostDirection": "",
            "unitType": "",
            "unitNumber": "",
            "city": "",
            "state": "",
            "zip": "",
            "zip4": "",
            "county": "",
            "longitude": "",
            "latitude": "",
            "startDate": "2015",
            "endDate": "",
            "duration": "6 years 10 months",
            "professionalTitles": [
              "CLIENT PARTNER",
              "DIRECTOR OF STRATEGY",
              "PRODUCT MANAGER - ECOSYSTEM",
              "FOUNDER",
              "ADJUNCT PROFESSOR OF BUSINESS",
              "STRATEGIST AND PRESIDENT",
              "CONSULTING MANAGER (STRATEGY CONSULTANT)",
              "PROJECT MANAGEMENT CONSULTANT",
              "TELECOMMUNICATIONS ANALYST",
              "NEW ASSOCIATE TECHNOLOGY ANALYST"
            ],
            "headquarters": "",
            "type": "Privately Held",
            "parentIndustry": "",
            "industry": "",
            "status": "",
            "email": "",
            "website": "WEBSITE.COM",
            "companySocialUrl": "www.linkedin.com/company/hot-dog-llc",
            "crunchBaseURL": "",
            "founded": "2008",
            "malePercent": "",
            "femalePercent": "",
            "medianAge": "",
            "medianTenure": "",
            "size": "11-50",
            "socialFollowers": "461 or more",
            "revenueRange": "",
            "sicCode": "",
            "sicDescription": "",
            "naics": "",
            "naicsDescription": "",
            "naicsDescription2digit": "",
            "naicsDescription3digit": ""
          },
          {
            "employer": "HOT DOG, LLC",
            "jobTitle": "DIRECTOR OF STRATEGY",
            "level": "DIRECTOR-LEVEL",
            "department": "Marketing and Product",
            "houseNumber": "",
            "streetDirection": "",
            "streetName": "",
            "streetType": "",
            "streetPostDirection": "",
            "unitType": "",
            "unitNumber": "",
            "city": "",
            "state": "",
            "zip": "",
            "zip4": "",
            "county": "",
            "longitude": "",
            "latitude": "",
            "startDate": "2020",
            "endDate": "2022",
            "duration": "2 years",
            "professionalTitles": [
              "CLIENT PARTNER",
              "DIRECTOR OF STRATEGY",
              "PRODUCT MANAGER - ECOSYSTEM",
              "FOUNDER",
              "ADJUNCT PROFESSOR OF BUSINESS",
              "STRATEGIST AND PRESIDENT",
              "CONSULTING MANAGER (STRATEGY CONSULTANT)",
              "PROJECT MANAGEMENT CONSULTANT",
              "TELECOMMUNICATIONS ANALYST",
              "NEW ASSOCIATE TECHNOLOGY ANALYST"
            ],
            "headquarters": "",
            "type": "Privately Held",
            "parentIndustry": "",
            "industry": "",
            "status": "",
            "email": "",
            "website": "WEBSITE.NET",
            "companySocialUrl": "www.linkedin.com/company/hot-dog-llc",
            "crunchBaseURL": "",
            "founded": "2008",
            "malePercent": "",
            "femalePercent": "",
            "medianAge": "",
            "medianTenure": "",
            "size": "11-50",
            "socialFollowers": "461 or more",
            "revenueRange": "",
            "sicCode": "",
            "sicDescription": "",
            "naics": "",
            "naicsDescription": "",
            "naicsDescription2digit": "",
            "naicsDescription3digit": ""
          },
          {
            "employer": "HOT DOG, LLC",
            "jobTitle": "DIRECTOR OF STRATEGY",
            "level": "DIRECTOR-LEVEL",
            "department": "Marketing and Product",
            "houseNumber": "",
            "streetDirection": "",
            "streetName": "",
            "streetType": "",
            "streetPostDirection": "",
            "unitType": "",
            "unitNumber": "",
            "city": "",
            "state": "",
            "zip": "",
            "zip4": "",
            "county": "",
            "longitude": "",
            "latitude": "",
            "startDate": "2022",
            "endDate": "",
            "duration": "5 months",
            "professionalTitles": [
              "CLIENT PARTNER",
              "DIRECTOR OF STRATEGY",
              "PRODUCT MANAGER - ECOSYSTEM",
              "FOUNDER",
              "ADJUNCT PROFESSOR OF BUSINESS",
              "STRATEGIST AND PRESIDENT",
              "CONSULTING MANAGER (STRATEGY CONSULTANT)",
              "PROJECT MANAGEMENT CONSULTANT",
              "TELECOMMUNICATIONS ANALYST",
              "NEW ASSOCIATE TECHNOLOGY ANALYST"
            ],
            "headquarters": "",
            "type": "Privately Held",
            "parentIndustry": "",
            "industry": "",
            "status": "",
            "email": "",
            "website": "WEBSITE.NET",
            "companySocialUrl": "www.linkedin.com/company/hot-dog-llc",
            "crunchBaseURL": "",
            "founded": "2008",
            "malePercent": "",
            "femalePercent": "",
            "medianAge": "",
            "medianTenure": "",
            "size": "11-50",
            "socialFollowers": "461 or more",
            "revenueRange": "",
            "sicCode": "",
            "sicDescription": "",
            "naics": "",
            "naicsDescription": "",
            "naicsDescription2digit": "",
            "naicsDescription3digit": ""
          },
          {
            "employer": "OTHER COMPANY, INC.",
            "jobTitle": "CLIENT PARTNER",
            "level": "C-LEVEL",
            "department": "Support",
            "houseNumber": "",
            "streetDirection": "",
            "streetName": "",
            "streetType": "",
            "streetPostDirection": "",
            "unitType": "",
            "unitNumber": "",
            "city": "",
            "state": "",
            "zip": "",
            "zip4": "",
            "county": "",
            "longitude": "",
            "latitude": "",
            "startDate": "2015",
            "endDate": "",
            "duration": "6 years 10 months",
            "professionalTitles": [
              "CLIENT PARTNER",
              "DIRECTOR OF STRATEGY",
              "PRODUCT MANAGER - ECOSYSTEM",
              "FOUNDER",
              "ADJUNCT PROFESSOR OF BUSINESS",
              "STRATEGIST AND PRESIDENT",
              "CONSULTING MANAGER (STRATEGY CONSULTANT)",
              "PROJECT MANAGEMENT CONSULTANT",
              "TELECOMMUNICATIONS ANALYST",
              "NEW ASSOCIATE TECHNOLOGY ANALYST"
            ],
            "headquarters": "",
            "type": "",
            "parentIndustry": "",
            "industry": "",
            "status": "",
            "email": "",
            "website": "",
            "companySocialUrl": "",
            "crunchBaseURL": "",
            "founded": "",
            "malePercent": "",
            "femalePercent": "",
            "medianAge": "",
            "medianTenure": "",
            "size": "",
            "socialFollowers": "",
            "revenueRange": "",
            "sicCode": "",
            "sicDescription": "",
            "naics": "",
            "naicsDescription": "",
            "naicsDescription2digit": "",
            "naicsDescription3digit": ""
          },
          {
            "employer": "OTHER COMPANY, INC.",
            "jobTitle": "CLIENT PARTNER",
            "level": "C-LEVEL",
            "department": "Support",
            "houseNumber": "",
            "streetDirection": "",
            "streetName": "",
            "streetType": "",
            "streetPostDirection": "",
            "unitType": "",
            "unitNumber": "",
            "city": "",
            "state": "",
            "zip": "",
            "zip4": "",
            "county": "",
            "longitude": "",
            "latitude": "",
            "startDate": "2020",
            "endDate": "2022",
            "duration": "2 years",
            "professionalTitles": [
              "CLIENT PARTNER",
              "DIRECTOR OF STRATEGY",
              "PRODUCT MANAGER - ECOSYSTEM",
              "FOUNDER",
              "ADJUNCT PROFESSOR OF BUSINESS",
              "STRATEGIST AND PRESIDENT",
              "CONSULTING MANAGER (STRATEGY CONSULTANT)",
              "PROJECT MANAGEMENT CONSULTANT",
              "TELECOMMUNICATIONS ANALYST",
              "NEW ASSOCIATE TECHNOLOGY ANALYST"
            ],
            "headquarters": "",
            "type": "",
            "parentIndustry": "",
            "industry": "",
            "status": "",
            "email": "",
            "website": "",
            "companySocialUrl": "",
            "crunchBaseURL": "",
            "founded": "",
            "malePercent": "",
            "femalePercent": "",
            "medianAge": "",
            "medianTenure": "",
            "size": "",
            "socialFollowers": "",
            "revenueRange": "",
            "sicCode": "",
            "sicDescription": "",
            "naics": "",
            "naicsDescription": "",
            "naicsDescription2digit": "",
            "naicsDescription3digit": ""
          },
          {
            "employer": "OTHER COMPANY, INC.",
            "jobTitle": "CLIENT PARTNER",
            "level": "C-LEVEL",
            "department": "Support",
            "houseNumber": "",
            "streetDirection": "",
            "streetName": "",
            "streetType": "",
            "streetPostDirection": "",
            "unitType": "",
            "unitNumber": "",
            "city": "",
            "state": "",
            "zip": "",
            "zip4": "",
            "county": "",
            "longitude": "",
            "latitude": "",
            "startDate": "2022",
            "endDate": "",
            "duration": "5 months",
            "professionalTitles": [
              "CLIENT PARTNER",
              "DIRECTOR OF STRATEGY",
              "PRODUCT MANAGER - ECOSYSTEM",
              "FOUNDER",
              "ADJUNCT PROFESSOR OF BUSINESS",
              "STRATEGIST AND PRESIDENT",
              "CONSULTING MANAGER (STRATEGY CONSULTANT)",
              "PROJECT MANAGEMENT CONSULTANT",
              "TELECOMMUNICATIONS ANALYST",
              "NEW ASSOCIATE TECHNOLOGY ANALYST"
            ],
            "headquarters": "",
            "type": "",
            "parentIndustry": "",
            "industry": "",
            "status": "",
            "email": "",
            "website": "",
            "companySocialUrl": "",
            "crunchBaseURL": "",
            "founded": "",
            "malePercent": "",
            "femalePercent": "",
            "medianAge": "",
            "medianTenure": "",
            "size": "",
            "socialFollowers": "",
            "revenueRange": "",
            "sicCode": "",
            "sicDescription": "",
            "naics": "",
            "naicsDescription": "",
            "naicsDescription2digit": "",
            "naicsDescription3digit": ""
          },
          {
            "employer": "THIRD COMPANY",
            "jobTitle": "FOUNDER",
            "level": "C-LEVEL",
            "department": "Business Management",
            "houseNumber": "",
            "streetDirection": "",
            "streetName": "",
            "streetType": "",
            "streetPostDirection": "",
            "unitType": "",
            "unitNumber": "",
            "city": "",
            "state": "",
            "zip": "",
            "zip4": "",
            "county": "",
            "longitude": "",
            "latitude": "",
            "startDate": "2015",
            "endDate": "",
            "duration": "6 years 10 months",
            "professionalTitles": [
              "CLIENT PARTNER",
              "DIRECTOR OF STRATEGY",
              "PRODUCT MANAGER - ECOSYSTEM",
              "FOUNDER",
              "ADJUNCT PROFESSOR OF BUSINESS",
              "STRATEGIST AND PRESIDENT",
              "CONSULTING MANAGER (STRATEGY CONSULTANT)",
              "PROJECT MANAGEMENT CONSULTANT",
              "TELECOMMUNICATIONS ANALYST",
              "NEW ASSOCIATE TECHNOLOGY ANALYST"
            ],
            "headquarters": "",
            "type": "Self-Owned",
            "parentIndustry": "",
            "industry": "",
            "status": "",
            "email": "",
            "website": "",
            "companySocialUrl": "www.linkedin.com/company/thirdcompany",
            "crunchBaseURL": "",
            "founded": "",
            "malePercent": "",
            "femalePercent": "",
            "medianAge": "",
            "medianTenure": "",
            "size": "1",
            "socialFollowers": "",
            "revenueRange": "",
            "sicCode": "",
            "sicDescription": "",
            "naics": "",
            "naicsDescription": "",
            "naicsDescription2digit": "",
            "naicsDescription3digit": ""
          },
          {
            "employer": "THIRD COMPANY",
            "jobTitle": "FOUNDER",
            "level": "C-LEVEL",
            "department": "Business Management",
            "houseNumber": "",
            "streetDirection": "",
            "streetName": "",
            "streetType": "",
            "streetPostDirection": "",
            "unitType": "",
            "unitNumber": "",
            "city": "",
            "state": "",
            "zip": "",
            "zip4": "",
            "county": "",
            "longitude": "",
            "latitude": "",
            "startDate": "2020",
            "endDate": "2022",
            "duration": "2 years",
            "professionalTitles": [
              "CLIENT PARTNER",
              "DIRECTOR OF STRATEGY",
              "PRODUCT MANAGER - ECOSYSTEM",
              "FOUNDER",
              "ADJUNCT PROFESSOR OF BUSINESS",
              "STRATEGIST AND PRESIDENT",
              "CONSULTING MANAGER (STRATEGY CONSULTANT)",
              "PROJECT MANAGEMENT CONSULTANT",
              "TELECOMMUNICATIONS ANALYST",
              "NEW ASSOCIATE TECHNOLOGY ANALYST"
            ],
            "headquarters": "",
            "type": "Self-Owned",
            "parentIndustry": "",
            "industry": "",
            "status": "",
            "email": "",
            "website": "",
            "companySocialUrl": "www.linkedin.com/company/thirdcompany",
            "crunchBaseURL": "",
            "founded": "",
            "malePercent": "",
            "femalePercent": "",
            "medianAge": "",
            "medianTenure": "",
            "size": "1",
            "socialFollowers": "",
            "revenueRange": "",
            "sicCode": "",
            "sicDescription": "",
            "naics": "",
            "naicsDescription": "",
            "naicsDescription2digit": "",
            "naicsDescription3digit": ""
          },
          {
            "employer": "THIRD COMPANY",
            "jobTitle": "FOUNDER",
            "level": "C-LEVEL",
            "department": "Business Management",
            "houseNumber": "",
            "streetDirection": "",
            "streetName": "",
            "streetType": "",
            "streetPostDirection": "",
            "unitType": "",
            "unitNumber": "",
            "city": "",
            "state": "",
            "zip": "",
            "zip4": "",
            "county": "",
            "longitude": "",
            "latitude": "",
            "startDate": "2022",
            "endDate": "",
            "duration": "5 months",
            "professionalTitles": [
              "CLIENT PARTNER",
              "DIRECTOR OF STRATEGY",
              "PRODUCT MANAGER - ECOSYSTEM",
              "FOUNDER",
              "ADJUNCT PROFESSOR OF BUSINESS",
              "STRATEGIST AND PRESIDENT",
              "CONSULTING MANAGER (STRATEGY CONSULTANT)",
              "PROJECT MANAGEMENT CONSULTANT",
              "TELECOMMUNICATIONS ANALYST",
              "NEW ASSOCIATE TECHNOLOGY ANALYST"
            ],
            "headquarters": "",
            "type": "Self-Owned",
            "parentIndustry": "",
            "industry": "",
            "status": "",
            "email": "",
            "website": "",
            "companySocialUrl": "www.linkedin.com/company/thirdcompany",
            "crunchBaseURL": "",
            "founded": "",
            "malePercent": "",
            "femalePercent": "",
            "medianAge": "",
            "medianTenure": "",
            "size": "1",
            "socialFollowers": "",
            "revenueRange": "",
            "sicCode": "",
            "sicDescription": "",
            "naics": "",
            "naicsDescription": "",
            "naicsDescription2digit": "",
            "naicsDescription3digit": ""
          }
        ],
        "personLocation": [
          {
            "city": "HOUSTON",
            "state": "TX",
            "qualityOrder": 1
          }
        ],
        "workExperience": [
          {
            "expJobOrder": 1,
            "expJobTitle": "CLIENT PARTNER",
            "expCompanyProfileURL": "",
            "expCompany": "OTHER COMPANY, INC.",
            "expCompanyDetails": "",
            "expStartDate": "",
            "expEndDate": "",
            "expDuration": "5 months",
            "company": {
              "companyId": 0,
              "companyName": "OTHER COMPANY, INC.",
              "companyHouseNumber": "",
              "companyStreetDirection": "",
              "companyStreetName": "",
              "companyStreetType": "",
              "companyStreetPostDirection": "",
              "companyUnitType": "",
              "companyUnitNumber": "",
              "companyCity": "",
              "companyState": "",
              "companyZipCode": "",
              "companyZip4": "",
              "longitude": "",
              "latitude": "",
              "companyCounty": "",
              "companyCountry": "",
              "companyParentIndustry": "Media and Entertainment",
              "companyIndustry": "Media Production",
              "companyType": "Partnership",
              "companyStatus": "",
              "companySize": "1-10",
              "companyFounded": "2007",
              "companyWebSite": "WWW.WEBSITE.COM",
              "companySocialUrl": "www.linkedin.com/company/othercompany",
              "crunchBaseUrl": "",
              "companyMedianAge": "",
              "companyMedianTenure": "",
              "companyMalePercentage": "",
              "companyFemalePercentage": "",
              "companyEmail": "",
              "companyHeadQuarters": "Westville, VA",
              "companyAddress1": "",
              "companyAddress2": "",
              "fullAddress": "",
              "revenueRange": "",
              "sicCode": "",
              "sicDescription": "",
              "naics": "",
              "naicsDescription": "",
              "naicsDescription2digit": "",
              "naicsDescription3digit": "",
              "companyRoles": []
            }
          },
          {
            "expJobOrder": 2,
            "expJobTitle": "DIRECTOR OF STRATEGY",
            "expCompanyProfileURL": "",
            "expCompany": "HOT DOG, LLC",
            "expCompanyDetails": "Privately Held; 11-50 employees; Advertising Services",
            "expStartDate": "",
            "expEndDate": "",
            "expDuration": "2 years",
            "company": {
              "companyId": 0,
              "companyName": "HOT DOG, LLC",
              "companyHouseNumber": "",
              "companyStreetDirection": "",
              "companyStreetName": "",
              "companyStreetType": "",
              "companyStreetPostDirection": "",
              "companyUnitType": "",
              "companyUnitNumber": "",
              "companyCity": "",
              "companyState": "",
              "companyZipCode": "",
              "companyZip4": "",
              "longitude": "",
              "latitude": "",
              "companyCounty": "",
              "companyCountry": "",
              "companyParentIndustry": "",
              "companyIndustry": "",
              "companyType": "Privately Held",
              "companyStatus": "",
              "companySize": "11-50",
              "companyFounded": "2008",
              "companyWebSite": "WEBSITE.NET",
              "companySocialUrl": "www.linkedin.com/company/hot-dog-llc",
              "crunchBaseUrl": "",
              "companyMedianAge": "",
              "companyMedianTenure": "",
              "companyMalePercentage": "",
              "companyFemalePercentage": "",
              "companyEmail": "",
              "companyHeadQuarters": "",
              "companyAddress1": "",
              "companyAddress2": "",
              "fullAddress": "",
              "revenueRange": "",
              "sicCode": "",
              "sicDescription": "",
              "naics": "",
              "naicsDescription": "",
              "naicsDescription2digit": "",
              "naicsDescription3digit": "",
              "companyRoles": []
            }
          },
          {
            "expJobOrder": 3,
            "expJobTitle": "PRODUCT MANAGER - ECOSYSTEM",
            "expCompanyProfileURL": "",
            "expCompany": "COMPANY QUATRO",
            "expCompanyDetails": "",
            "expStartDate": "",
            "expEndDate": "",
            "expDuration": "10 months",
            "company": {
              "companyId": 0,
              "companyName": "COMPANY QUATRO",
              "companyHouseNumber": "",
              "companyStreetDirection": "",
              "companyStreetName": "",
              "companyStreetType": "",
              "companyStreetPostDirection": "",
              "companyUnitType": "",
              "companyUnitNumber": "",
              "companyCity": "",
              "companyState": "",
              "companyZipCode": "",
              "companyZip4": "",
              "longitude": "",
              "latitude": "",
              "companyCounty": "",
              "companyCountry": "",
              "companyParentIndustry": "",
              "companyIndustry": "",
              "companyType": "",
              "companyStatus": "",
              "companySize": "",
              "companyFounded": "",
              "companyWebSite": "",
              "companySocialUrl": "",
              "crunchBaseUrl": "",
              "companyMedianAge": "",
              "companyMedianTenure": "",
              "companyMalePercentage": "",
              "companyFemalePercentage": "",
              "companyEmail": "",
              "companyHeadQuarters": "",
              "companyAddress1": "",
              "companyAddress2": "",
              "fullAddress": "",
              "revenueRange": "",
              "sicCode": "",
              "sicDescription": "",
              "naics": "",
              "naicsDescription": "",
              "naicsDescription2digit": "",
              "naicsDescription3digit": "",
              "companyRoles": []
            }
          },
          {
            "expJobOrder": 4,
            "expJobTitle": "FOUNDER",
            "expCompanyProfileURL": "",
            "expCompany": "THIRD COMPANY",
            "expCompanyDetails": "Self-Owned; 1 employees; Business Consulting and Services",
            "expStartDate": "",
            "expEndDate": "",
            "expDuration": "6 years 10 months",
            "company": {
              "companyId": 0,
              "companyName": "THIRD COMPANY",
              "companyHouseNumber": "",
              "companyStreetDirection": "",
              "companyStreetName": "",
              "companyStreetType": "",
              "companyStreetPostDirection": "",
              "companyUnitType": "",
              "companyUnitNumber": "",
              "companyCity": "",
              "companyState": "",
              "companyZipCode": "",
              "companyZip4": "",
              "longitude": "",
              "latitude": "",
              "companyCounty": "",
              "companyCountry": "",
              "companyParentIndustry": "",
              "companyIndustry": "",
              "companyType": "Self-Owned",
              "companyStatus": "",
              "companySize": "1",
              "companyFounded": "",
              "companyWebSite": "",
              "companySocialUrl": "www.linkedin.com/company/thirdcompany",
              "crunchBaseUrl": "",
              "companyMedianAge": "",
              "companyMedianTenure": "",
              "companyMalePercentage": "",
              "companyFemalePercentage": "",
              "companyEmail": "",
              "companyHeadQuarters": "",
              "companyAddress1": "",
              "companyAddress2": "",
              "fullAddress": "",
              "revenueRange": "",
              "sicCode": "",
              "sicDescription": "",
              "naics": "",
              "naicsDescription": "",
              "naicsDescription2digit": "",
              "naicsDescription3digit": "",
              "companyRoles": []
            }
          },
          {
            "expJobOrder": 5,
            "expJobTitle": "PROFESSOR OF BUSINESS",
            "expCompanyProfileURL": "",
            "expCompany": "ABC COLLEGE",
            "expCompanyDetails": "",
            "expStartDate": "",
            "expEndDate": "",
            "expDuration": "10 months",
            "company": {
              "companyId": 0,
              "companyName": "ABC COLLEGE",
              "companyHouseNumber": "",
              "companyStreetDirection": "",
              "companyStreetName": "",
              "companyStreetType": "",
              "companyStreetPostDirection": "",
              "companyUnitType": "",
              "companyUnitNumber": "",
              "companyCity": "",
              "companyState": "",
              "companyZipCode": "",
              "companyZip4": "",
              "longitude": "",
              "latitude": "",
              "companyCounty": "",
              "companyCountry": "",
              "companyParentIndustry": "",
              "companyIndustry": "",
              "companyType": "",
              "companyStatus": "",
              "companySize": "",
              "companyFounded": "",
              "companyWebSite": "",
              "companySocialUrl": "",
              "crunchBaseUrl": "",
              "companyMedianAge": "",
              "companyMedianTenure": "",
              "companyMalePercentage": "",
              "companyFemalePercentage": "",
              "companyEmail": "",
              "companyHeadQuarters": "",
              "companyAddress1": "",
              "companyAddress2": "",
              "fullAddress": "",
              "revenueRange": "",
              "sicCode": "",
              "sicDescription": "",
              "naics": "",
              "naicsDescription": "",
              "naicsDescription2digit": "",
              "naicsDescription3digit": "",
              "companyRoles": []
            }
          },
          {
            "expJobOrder": 6,
            "expJobTitle": "PRESIDENT",
            "expCompanyProfileURL": "",
            "expCompany": "FIFTH COMPANY",
            "expCompanyDetails": "",
            "expStartDate": "",
            "expEndDate": "",
            "expDuration": "6 years 2 months",
            "company": {
              "companyId": 0,
              "companyName": "FIFTH COMPANY",
              "companyHouseNumber": "",
              "companyStreetDirection": "",
              "companyStreetName": "",
              "companyStreetType": "",
              "companyStreetPostDirection": "",
              "companyUnitType": "",
              "companyUnitNumber": "",
              "companyCity": "",
              "companyState": "",
              "companyZipCode": "",
              "companyZip4": "",
              "longitude": "",
              "latitude": "",
              "companyCounty": "",
              "companyCountry": "",
              "companyParentIndustry": "",
              "companyIndustry": "",
              "companyType": "",
              "companyStatus": "",
              "companySize": "",
              "companyFounded": "",
              "companyWebSite": "",
              "companySocialUrl": "",
              "crunchBaseUrl": "",
              "companyMedianAge": "",
              "companyMedianTenure": "",
              "companyMalePercentage": "",
              "companyFemalePercentage": "",
              "companyEmail": "",
              "companyHeadQuarters": "",
              "companyAddress1": "",
              "companyAddress2": "",
              "fullAddress": "",
              "revenueRange": "",
              "sicCode": "",
              "sicDescription": "",
              "naics": "",
              "naicsDescription": "",
              "naicsDescription2digit": "",
              "naicsDescription3digit": "",
              "companyRoles": []
            }
          },
          {
            "expJobOrder": 7,
            "expJobTitle": "CONSULTING MANAGER (STRATEGY CONSULTANT)",
            "expCompanyProfileURL": "",
            "expCompany": "SIXTH COMPANY, INC.",
            "expCompanyDetails": "Privately Held; 51-200 employees; Business Consulting and Services",
            "expStartDate": "",
            "expEndDate": "",
            "expDuration": "1 year 11 months",
            "company": {
              "companyId": 0,
              "companyName": "SIXTH COMPANY, INC.",
              "companyHouseNumber": "",
              "companyStreetDirection": "",
              "companyStreetName": "",
              "companyStreetType": "",
              "companyStreetPostDirection": "",
              "companyUnitType": "",
              "companyUnitNumber": "",
              "companyCity": "",
              "companyState": "",
              "companyZipCode": "",
              "companyZip4": "",
              "longitude": "",
              "latitude": "",
              "companyCounty": "",
              "companyCountry": "",
              "companyParentIndustry": "",
              "companyIndustry": "",
              "companyType": "",
              "companyStatus": "",
              "companySize": "",
              "companyFounded": "",
              "companyWebSite": "",
              "companySocialUrl": "",
              "crunchBaseUrl": "",
              "companyMedianAge": "",
              "companyMedianTenure": "",
              "companyMalePercentage": "",
              "companyFemalePercentage": "",
              "companyEmail": "",
              "companyHeadQuarters": "",
              "companyAddress1": "",
              "companyAddress2": "",
              "fullAddress": "",
              "revenueRange": "",
              "sicCode": "",
              "sicDescription": "",
              "naics": "",
              "naicsDescription": "",
              "naicsDescription2digit": "",
              "naicsDescription3digit": "",
              "companyRoles": []
            }
          },
          {
            "expJobOrder": 8,
            "expJobTitle": "PROJECT MANAGEMENT CONSULTANT",
            "expCompanyProfileURL": "",
            "expCompany": "SEVENTH COMPANY",
            "expCompanyDetails": "Public Company; 1001-5000 employees; Financial Services",
            "expStartDate": "",
            "expEndDate": "",
            "expDuration": "3 months",
            "company": {
              "companyId": 0,
              "companyName": "SEVENTH COMPANY",
              "companyHouseNumber": "",
              "companyStreetDirection": "",
              "companyStreetName": "",
              "companyStreetType": "",
              "companyStreetPostDirection": "",
              "companyUnitType": "",
              "companyUnitNumber": "",
              "companyCity": "",
              "companyState": "",
              "companyZipCode": "",
              "companyZip4": "",
              "longitude": "",
              "latitude": "",
              "companyCounty": "",
              "companyCountry": "",
              "companyParentIndustry": "",
              "companyIndustry": "",
              "companyType": "",
              "companyStatus": "",
              "companySize": "",
              "companyFounded": "",
              "companyWebSite": "",
              "companySocialUrl": "",
              "crunchBaseUrl": "",
              "companyMedianAge": "",
              "companyMedianTenure": "",
              "companyMalePercentage": "",
              "companyFemalePercentage": "",
              "companyEmail": "",
              "companyHeadQuarters": "",
              "companyAddress1": "",
              "companyAddress2": "",
              "fullAddress": "",
              "revenueRange": "",
              "sicCode": "",
              "sicDescription": "",
              "naics": "",
              "naicsDescription": "",
              "naicsDescription2digit": "",
              "naicsDescription3digit": "",
              "companyRoles": []
            }
          },
          {
            "expJobOrder": 9,
            "expJobTitle": "DATA ANALYST",
            "expCompanyProfileURL": "",
            "expCompany": "EIGHTH COMPANY",
            "expCompanyDetails": "",
            "expStartDate": "",
            "expEndDate": "",
            "expDuration": "1 year 4 months",
            "company": {
              "companyId": 0,
              "companyName": "EIGHTH COMPANY",
              "companyHouseNumber": "",
              "companyStreetDirection": "",
              "companyStreetName": "",
              "companyStreetType": "",
              "companyStreetPostDirection": "",
              "companyUnitType": "",
              "companyUnitNumber": "",
              "companyCity": "",
              "companyState": "",
              "companyZipCode": "",
              "companyZip4": "",
              "longitude": "",
              "latitude": "",
              "companyCounty": "",
              "companyCountry": "",
              "companyParentIndustry": "",
              "companyIndustry": "",
              "companyType": "",
              "companyStatus": "",
              "companySize": "",
              "companyFounded": "",
              "companyWebSite": "",
              "companySocialUrl": "",
              "crunchBaseUrl": "",
              "companyMedianAge": "",
              "companyMedianTenure": "",
              "companyMalePercentage": "",
              "companyFemalePercentage": "",
              "companyEmail": "",
              "companyHeadQuarters": "",
              "companyAddress1": "",
              "companyAddress2": "",
              "fullAddress": "",
              "revenueRange": "",
              "sicCode": "",
              "sicDescription": "",
              "naics": "",
              "naicsDescription": "",
              "naicsDescription2digit": "",
              "naicsDescription3digit": "",
              "companyRoles": []
            }
          },
          {
            "expJobOrder": 10,
            "expJobTitle": "TECHNOLOGY ANALYST",
            "expCompanyProfileURL": "",
            "expCompany": "EIGHTH COMPANY",
            "expCompanyDetails": "",
            "expStartDate": "",
            "expEndDate": "",
            "expDuration": "1 year 10 months",
            "company": {
              "companyId": 0,
              "companyName": "EIGHTH COMPANY",
              "companyHouseNumber": "",
              "companyStreetDirection": "",
              "companyStreetName": "",
              "companyStreetType": "",
              "companyStreetPostDirection": "",
              "companyUnitType": "",
              "companyUnitNumber": "",
              "companyCity": "",
              "companyState": "",
              "companyZipCode": "",
              "companyZip4": "",
              "longitude": "",
              "latitude": "",
              "companyCounty": "",
              "companyCountry": "",
              "companyParentIndustry": "",
              "companyIndustry": "",
              "companyType": "",
              "companyStatus": "",
              "companySize": "",
              "companyFounded": "",
              "companyWebSite": "",
              "companySocialUrl": "",
              "crunchBaseUrl": "",
              "companyMedianAge": "",
              "companyMedianTenure": "",
              "companyMalePercentage": "",
              "companyFemalePercentage": "",
              "companyEmail": "",
              "companyHeadQuarters": "",
              "companyAddress1": "",
              "companyAddress2": "",
              "fullAddress": "",
              "revenueRange": "",
              "sicCode": "",
              "sicDescription": "",
              "naics": "",
              "naicsDescription": "",
              "naicsDescription2digit": "",
              "naicsDescription3digit": "",
              "companyRoles": []
            }
          }
        ],
        "impliedInfo": [],
        "miscInfo": [],
        "groups": [],
        "personUrls": [
          "https://www.linkedin.com/in/johndoe"
        ],
        "socialConnections": "500+",
        "certifications": [],
        "vendor": ""
      }
    ],
    "counts": {
      "searchResults": 1
    },
    "pagination": {
      "currentPageNumber": 1,
      "resultsPerPage": 1,
      "totalPages": 1,
      "totalResults": 134
    },
    "searchCriteria": [],
    "totalRequestExecutionTimeMs": 2089,
    "requestId": "688f57c1-2b06-4b50-a10a-16a1d8c7d76a",
    "requestType": "WorkplaceSearch",
    "requestTime": "2023-04-06T13:47:25.3444121-07:00",
    "isError": false
  }